#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-0 --primary --mode 1920x1080 --output HDMI-1 --mode 1440x900 --right-of HDMI-0

nitrogen --restore
picom &
$HOME/github/eww/target/release/eww open bar


bspc monitor HDMI-0 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII X

bspc config border_width   5
bspc config window_gap  20
bspc config bottom_padding 5
bspc config top_padding 40
bspc config -m HDMI-1 top_padding 5
bspc config right_padding 5
bspc config left_padding 5

bspc config normal_border_color    \#dcd3c6
bspc config focused_border_color   \#93836c
bspc config presel_feedback_color  \#dcd3c6

bspc config split_ratio            0.5
bspc config borderless_monocle     false
bspc config gapless_monocle        false


bspc rule -a "mpv" layer=above
bspc rule -a Emacs state=tiled
